version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: images_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_container
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: minio_container
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  api:
    build: ./api-service
    container_name: api_service
    env_file:
      - api-service/.env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres

  crawler:
    build: ./crawler-worker
    container_name: crawler_worker
    env_file:
      - crawler-worker/.env
    depends_on:
      - redis

  uploader:
    build: ./uploader-worker
    container_name: uploader_worker
    env_file:
      - uploader-worker/.env
    depends_on:
      - redis
      - minio

  metadata:
    build: ./metadata-worker
    container_name: metadata_worker
    env_file:
      - metadata-worker/.env
    depends_on:
      - redis
      - postgres

volumes:
  postgres_data:
  minio_data:
